name: Build and Securely Push Image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Application branch to build"
        required: true
        type: string

      image_tag:
        description: "Docker image tag"
        required: true
        type: string

      image_name:
        description: "Docker image name"
        required: true
        type: string

jobs:
  build-and-security-scan:
    runs-on: ubuntu-latest

    steps:

      # ==========================================
      # 1. Checkout application code
      # ==========================================
      - name: Checkout application code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      # ==========================================
      # 2. Semgrep - SAST
      # ==========================================
      - name: Run Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: auto

      # ==========================================
      # 3. SonarQube - Code Quality / Security
      # ==========================================
      #- name: SonarQube Scan
      #  uses: SonarSource/sonarqube-scan-action@v6
      #  env:
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #    SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # ==========================================
      # 4. Build Docker image
      # ==========================================
      - name: Build Docker image
        run: |
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}:${{ inputs.image_tag }}"
          echo "Building ${IMAGE}"
          docker build -t "${IMAGE}" .

      # ==========================================
      # 5. Trivy - Container Image Scan
      # ==========================================
      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}:${{ inputs.image_tag }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"

      # ==========================================
      # 6. Login to Docker Hub
      # ==========================================
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ==========================================
      # 7. Push Docker image
      # ==========================================
      - name: Push Docker image
        run: |
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}:${{ inputs.image_tag }}"
          echo "Pushing ${IMAGE}"
          docker push "${IMAGE}"
